
from itertools import batched

rom = open("model3.rom", "rb").read()

print("// Generated by make_roms.py. Do not modify.")
print()
print('#include "model3_rom.h"')
print()
print("size_t MODEL3_ROM_SIZE = %d;" % len(rom));
print("uint8_t MODEL3_ROM[] = {");
for x in batched(rom, 16):
    print("    " + "".join("0x%02X, " % b for b in x))
print("};")
