#!/bin/bash

if [ $(ls -1 /dev/tty.usbmodem* | wc -l) != 1 ]; then
    echo "Can't determine TTY."
    exit 1
fi

DEVICE=$(echo /dev/tty.usbmodem*)

# https://github.com/bradgrantham/simple-serial-terminal
echo "Putting Pico in program mode..."
~/others/simple-serial-terminal/serial --monitor --expect-disconnect $DEVICE 1200

echo "Waiting for Pico to restart..."
sleep 2

echo "Programming pico..."
cp build/micro-model-3.uf2 /Volumes/RPI-RP2

