#!/bin/bash

DEVICE=/dev/tty.usbmodem1301

# This puts the Pico into program mode.
~/others/simple-serial-terminal/serial --monitor $DEVICE 1200

# Wait for it to be ready and mount the volume.
sleep 2

# Copy our binary to its volume.
cp build/micro-model-3.uf2 /Volumes/RPI-RP2

